# _config.yml

# ---------------------------------------------------------
remote_theme: mmistakes/minimal-mistakes
# ---------------------------------------------------------

# 你的个人信息设置
title: "Jiandong Ding"
locale: "en-US" # 建议加上这行，防止字符编码报错
author:
  name: "Jiandong Ding (丁 建栋)"
  avatar: "/assets/images/Profile.jpg"
  bio: "Principle expert at **Huawei Technologies**.<br>Bridging **Biological Sequences** & **User Behaviors**."
  location: "Shanghai, China"
  links:
    - label: "Publications"
      icon: "fas fa-fw fa-graduation-cap"
      url: "/publications"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jiandong-ding-60498833/"

# 插件支持（建议加上，确保功能正常）
plugins:
  - jekyll-include-cache


#    - label: "Google Scholar"
#      icon: "fas fa-fw fa-file-alt"
#      url: "https://scholar.google.com/citations?hl=zh-CN&user=5-e7wi4AAAAJ&view_op=list_works&sortby=pubdate"

