# _config.yml

# ---------------------------------------------------------
# ğŸ‘‡ ã€å…³é”®æ­¥éª¤ã€‘å¿…é¡»æ¿€æ´»è¿™ä¸ªä¸»é¢˜ï¼Œä½ çš„ bio å’Œ links æ‰ä¼šæ˜¾ç¤ºï¼
remote_theme: mmistakes/minimal-mistakes
# ---------------------------------------------------------

# ä½ çš„ä¸ªäººä¿¡æ¯è®¾ç½®
title: "Jiandong Ding"
locale: "en-US" # å»ºè®®åŠ ä¸Šè¿™è¡Œï¼Œé˜²æ­¢å­—ç¬¦ç¼–ç æŠ¥é”™
author:
  name: "Jiandong Ding"
  avatar: "/assets/images/Profile.jpg"
  bio: "Technical expert at **Huawei Technologies**.<br>Bridging **Biological Sequences** & **User Behaviors**."
  location: "Shanghai, China"
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=zh-CN&user=5-e7wi4AAAAJ&view_op=list_works&sortby=pubdate"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jiandong-ding-60498833/"
    - label: "Publications"
      icon: "fas fa-fw fa-file-alt"
      url: "/publications/"

# æ’ä»¶æ”¯æŒï¼ˆå»ºè®®åŠ ä¸Šï¼Œç¡®ä¿åŠŸèƒ½æ­£å¸¸ï¼‰
plugins:
  - jekyll-include-cache
